package com.ronnaces.loong.codegen.api.mapper;

import com.ronnaces.loong.codegen.api.entity.Datasource;
import com.ronnaces.loong.codegen.api.entity.DatasourceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DatasourceMapper {

    void createTable();

    List<String> showTables();

    List<Datasource> selectList();

    Datasource selectById(String id);

    void deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    long countByExample(DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    int deleteByExample(DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    int insert(Datasource row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    int insertSelective(Datasource row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    List<Datasource> selectByExample(DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    Datasource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Datasource row, @Param("example") DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Datasource row, @Param("example") DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Datasource row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Datasource row);

    int updateById(Datasource row);

}